# user will give us the large document then model will give us the notes and quizes 
# notes will be generated by the model 1 
# quiz will be generated by model 2 

# and third model 3 will combine / merge and display 

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_huggingface import HuggingFaceEndpoint
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate

from langchain_core.output_parsers import StrOutputParser

from langchain_core.runnables import RunnableParallel


load_dotenv()


model1 =ChatGoogleGenerativeAI(model='gemini-3.1-flash-lite')

model2 = HuggingFaceEndpoint(
    repo_id="CohereLabs/North-Mini-Code-1.0",
    task="text-generation",
    max_new_tokens=512
)

model3 = HuggingFaceEndpoint(
    repo_id="nvidia/Qwen3.6-35B-A3B-NVFP4",
    task="text-generation",
    temperature=0.7, 
    max_new_tokens=512 
)


prompt1 = PromptTemplate(
    template='Generate a short and simple notes from the following text : \n {text}',
    input_variables=['text']
)

prompt2 = PromptTemplate(
    template="Generate a five short question answers from the follwing text : \n {text}",
    input_variables=['text']
)

prompt3 = PromptTemplate(
    template="Merge the provided notes and quizes into a single document \n notes ->  {notes} and \n quizzes -> {quizzes}",
    input_variables=['notes','quizzes']
)


parser = StrOutputParser()


# now paraller chaining 

parallel_chain = RunnableParallel(
    {
        "notes": prompt1 | model1 | parser,
        "quizzes": prompt2 | model2 | parser
    }
)

merged_chain = prompt3 | model3 | parser

chain = parallel_chain | merged_chain 

text = """

scikit-learn (formerly scikits.learn and also known as sklearn) is a free and open-source machine learning library for the Python programming language.[3] It features various classification, regression and clustering algorithms including support-vector machines, random forests, gradient boosting, k-means and DBSCAN, and is designed to interoperate with the Python numerical and scientific libraries NumPy and SciPy. Scikit-learn is a NumFOCUS fiscally sponsored project.[4]

Overview
The scikit-learn project started as scikits.learn, a Google Summer of Code project by French data scientist David Cournapeau. The name of the project derives from its role as a "scientific toolkit for machine learning", originally developed and distributed as a third-party extension to SciPy.[5] The original codebase was later rewritten by other developers.[who?] In 2010, contributors Fabian Pedregosa, Gaël Varoquaux, Alexandre Gramfort and Vincent Michel, from the French Institute for Research in Computer Science and Automation in Saclay, France, took leadership of the project and released the first public version of the library on February 1, 2010.[6] In November 2012, scikit-learn as well as scikit-image were described as two of the "well-maintained and popular" scikits libraries.[7] In 2019, it was noted that scikit-learn is one of the most popular machine learning libraries on GitHub.[8] At that time, the project had over 1,400 contributors and the documentation received 42 million visits in 2018.[9] According to a 2022 Kaggle survey of nearly 24,000 respondents from 173 countries, scikit-learn was identified as the most widely used machine learning framework.[10]

Features
Large catalogue of well-established machine learning algorithms and data pre-processing methods (i.e. feature engineering)
Utility methods for common data-science tasks, such as splitting data into train and test sets, cross-validation and grid search
Consistent way of running machine learning models (estimator.fit() and estimator.predict()), which libraries can implement
Declarative way of structuring a data science process (the Pipeline), including data pre-processing and model fitting

"""
result = chain.invoke({'text': text})

print(result)

chain.get_graph().print_ascii()